-- Improved pesticide-class classifier (reduces the 'other' and 'unknown' buckets).
-- Class names MUST match index.html CLASS_COLORS: herbicide, insecticide, fungicide,
-- fumigant, rodenticide, growth_regulator, adjuvant, other, unknown.
-- Keep build/aggregate.py's classifier in sync with this.
--
-- Two arities:
--   chem_class(ai)            - by active ingredient (used by the functional index)
--   chem_class(ai, product)   - same, but when the AI is blank, recover spray
--                               adjuvants/surfactants from the PRODUCT name (the
--                               biggest blank-AI bucket is adjuvant products).
-- Order matters: the first matching branch wins.

create or replace function public.chem_class(ai text)
returns text language sql immutable as $$
  select case
    when ai is null or ai = '' then 'unknown'
    when upper(ai) ~ 'GLYPHOSATE|GLUFOSINATE|OXYFLUORFEN|PENDIMETHALIN|INDAZIFLAM|SAFLUFENACIL|CLETHODIM|SETHOXYDIM|CARFENTRAZONE|PYRAFLUFEN|TRIFLURALIN|PARAQUAT|DIURON|2,4-D|DICAMBA|ATRAZINE|SIMAZINE|METOLACHLOR|FLUMIOXAZIN|IMAZAPYR|IMAZAMOX|IMAZETHAPYR|IMAZAQUIN|TRICLOPYR|CLOPYRALID|AMINOPYRALID|HEXAZINONE|NORFLURAZON|BROMACIL|NAPROPAMIDE|METRIBUZIN|LINURON|PRODIAMINE|ISOXABEN|MESOTRIONE|FLUROXYPYR|\mMCPA\M|BENTAZON|PRONAMIDE|PROPYZAMIDE|DIQUAT|BENSULIDE|CHLORTHAL|PROPANIL|SULFURON|METURON|QUIZALOFOP|FLUAZIFOP|FENOXAPROP|OXADIAZON|OXADIARGYL|SULFENTRAZONE|FOMESAFEN|ACIFLUORFEN|LACTOFEN|ORYZALIN|DITHIOPYR|FLURIDONE|TOPRAMEZONE|TEMBOTRIONE|PYROXASULFONE|DIMETHENAMID|ACETOCHLOR|ALACHLOR|ETHALFLURALIN|FLUMETSULAM|HALAUXIFEN|FLORASULAM|PICLORAM|CYCLOATE|MOLINATE|THIOBENCARB|TRIBENURON' then 'herbicide'
    when upper(ai) ~ 'THRIN|CLOPRID|IMIDACLOPRID|ABAMECTIN|SPINOSAD|SPINETORAM|SPIROTETRAMAT|SPIROMESIFEN|SPIRODICLOFEN|FIPRONIL|INDOXACARB|CHLORANTRANILIPROLE|CYANTRANILIPROLE|TETRANILIPROLE|CYCLANILIPROLE|METHOXYFENOZIDE|TEBUFENOZIDE|CHROMAFENOZIDE|DINOTEFURAN|THIAMETHOXAM|CLOTHIANIDIN|ACETAMIPRID|METHOMYL|PYRIPROXYFEN|FENOXYCARB|KINOPRENE|HYDROPRENE|METHOPRENE|SULFOXAFLOR|FLUPYRADIFURONE|FLUPYRIMIN|TRIFLUMEZOPYRIM|PYRETHRIN|PIPERONYL|AZADIRACHTIN|NEEM|MALATHION|CHLORPYRIFOS|CARBARYL|OXAMYL|DIAZINON|ACEPHATE|DIMETHOATE|NALED|BUPROFEZIN|ETOXAZOLE|BIFENAZATE|FLONICAMID|EMAMECTIN|MILBEMECTIN|HEXYTHIAZOX|PYMETROZINE|NOVALURON|LUFENURON|DIFLUBENZURON|CYROMAZINE|CHLORFENAPYR|CYFLUMETOFEN|FENPYROXIMATE|ACEQUINOCYL|PROPARGITE|FENBUTATIN|METAFLUMIZONE|AFIDOPYROPEN|TOLFENPYRAD|BROFLANILIDE|ISOCYCLOSERAM|THURINGIENSIS|BEAUVERIA|METARHIZIUM|BURKHOLDERIA|CHROMOBACTERIUM|\mBORIC\M|BORATE|DIATOMACEOUS' then 'insecticide'
    when upper(ai) ~ 'STROBIN|CONAZOLE|MANCOZEB|CHLOROTHALONIL|COPPER|\mSULFUR\M|PHOSPHITE|FOSETYL|BOSCALID|FLUOPYRAM|FLUOPICOLIDE|CAPTAN|FOLPET|MYCLOBUTANIL|FLUDIOXONIL|IPRODIONE|METALAXYL|MEFENOXAM|CYPRODINIL|PYRIMETHANIL|FENHEXAMID|ZIRAM|THIRAM|METIRAM|THIOPHANATE|FLUAZINAM|PENTHIOPYRAD|FLUXAPYROXAD|PYDIFLUMETOFEN|ISOFETAMID|MANDIPROPAMID|CYAZOFAMID|CYMOXANIL|ZOXAMIDE|FAMOXADONE|FENAMIDONE|DIMETHOMORPH|VALIFENALATE|ETHABOXAM|OXATHIAPIPROLIN|PROPAMOCARB|DODINE|FLUTRIAFOL|FLUTOLANIL|TOLCLOFOS|METRAFENONE|QUINOXYFEN|CYFLUFENAMID|ACIBENZOLAR|POLYOXIN|BICARBONATE|PEROXYACETIC|HYDROGEN PEROXIDE|IMAZALIL|PROCHLORAZ|TRIFLUMIZOLE|SEDAXANE|BENZOVINDIFLUPYR|SUBTILIS|AMYLOLIQUEFACIENS|\mPUMILUS\M|REYNOUTRIA|MANDESTROBIN' then 'fungicide'
    when upper(ai) ~ 'DIPHACINONE|BRODIFACOUM|DIFENACOUM|BROMADIOLONE|FLOCOUMAFEN|CHLOROPHACINONE|WARFARIN|ZINC PHOSPHIDE|CHOLECALCIFEROL|DIFETHIALONE|BROMETHALIN|STRYCHNINE' then 'rodenticide'
    when upper(ai) ~ '1,3-DICHLOROPROPENE|METAM|CHLOROPICRIN|DAZOMET|METHYL BROMIDE|METHYL IODIDE|TELONE|DITHIOCARBAMATE|ISOTHIOCYANATE|SULFURYL|ALUMINUM PHOSPHIDE|MAGNESIUM PHOSPHIDE|PHOSPHINE' then 'fumigant'
    when upper(ai) ~ 'MINERAL OIL|PETROLEUM|\mSOAP\M|KAOLIN|FATTY ACID|SPRAY OIL|POLYOXYETHYLENE|NONYLPHENOL|ALCOHOL ETHOXYLATE|LECITHIN|POLYDIMETHYLSILOXANE|SORBITAN|POLYETHYLENE GLYCOL' then 'adjuvant'
    when upper(ai) ~ 'GIBBERELL|ETHEPHON|PACLOBUTRAZOL|ABSCISIC|MEPIQUAT|TRINEXAPAC|FORCHLORFENURON|PROHEXADION|CHLORMEQUAT|FLUMETRALIN|DAMINOZIDE|CYCLANILIDE|NAPHTHALENEACETIC|METHYLCYCLOPROPENE' then 'growth_regulator'
    else 'other' end;
$$;

create or replace function public.chem_class(ai text, product text)
returns text language sql immutable as $$
  select case
    when ai is not null and ai <> '' then public.chem_class(ai)
    when product is null or product = '' then 'unknown'
    when upper(product) ~ 'SURFACTANT|ADJUVANT|SPREADER|STICKER|\mMSO\M|\mNIS\M|\mCOC\M|CROP OIL|SEED OIL|METHYLATED|ORGANOSILICONE|SILICONE|SILWET|NONIONIC|WETTING|PENETRANT|ANTIFOAM|DEFOAM|FOAM FIGHTER|BUFFER|ACIDIFIER|DYNE-AMIC|LI 700|SYL-TAC|SYL-COAT|LIBERATE|KINETIC|NU FILM|NU-FILM|ACTIVATOR 90|LATRON|MSO CONCENTRATE|PRO 90' then 'adjuvant'
    else 'unknown' end;
$$;
